# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_first_name', models.CharField(blank=True, max_length=100)),
                ('owner_last_name', models.CharField(blank=True, max_length=100)),
                ('owner_middle_initial', models.CharField(blank=True, max_length=10)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('owner_address1', models.CharField(blank=True, max_length=200)),
                ('owner_address2', models.CharField(blank=True, max_length=200)),
                ('owner_city', models.CharField(blank=True, max_length=100)),
                ('owner_state', models.CharField(blank=True, max_length=50)),
                ('owner_zip', models.CharField(blank=True, max_length=20)),
                ('owner_country', models.CharField(blank=True, default='USA', max_length=100)),
                ('google_phone', models.CharField(blank=True, max_length=30)),
                ('email_agent', models.EmailField(blank=True, max_length=254)),
                ('salutation', models.TextField(blank=True)),
                ('closing', models.TextField(blank=True)),
                ('email_confirmation_body', models.TextField(blank=True)),
                ('ein', models.CharField(blank=True, max_length=50)),
                ('state_tax_reg_number', models.CharField(blank=True, max_length=50)),
                ('state_occupancy_tax_number', models.CharField(blank=True, max_length=50)),
                ('paypal', models.CharField(blank=True, max_length=200)),
                ('amazon_prime', models.CharField(blank=True, max_length=200)),
                ('tax_rate', models.DecimalField(decimal_places=4, default='0.1500', max_digits=5)),
                ('mileage_rate', models.DecimalField(decimal_places=4, default='0.5400', max_digits=5)),
                ('service_types', models.TextField(blank=True, help_text='One service type per line')),
                ('maintenance_types', models.TextField(blank=True, help_text='One maintenance type per line')),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
