# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_category', models.CharField(blank=True, choices=[('Capital Improvement', 'Capital Improvement'), ('Insurance', 'Insurance'), ('Maintenance', 'Maintenance'), ('Tax', 'Tax'), ('Travel', 'Travel')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Check', 'Check'), ('Amazon', 'Amazon'), ('PayPal', 'PayPal'), ('Venmo', 'Venmo')], max_length=50)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('maintenance_trip', models.BooleanField(default=False)),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('meal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('cost_per', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('replaced_broken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
