# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Fall', 'Fall'), ('Early Spring', 'Early Spring'), ('Late Spring', 'Late Spring')], max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('rate_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_weekly_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weekly Rate (CC)')),
                ('rate_daily_cc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Daily Rate (CC)')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleaning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('arrive_time', models.TimeField(blank=True, null=True)),
                ('leave_time', models.TimeField(blank=True, null=True)),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('pets', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=200)),
                ('other_needs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('Prior', 'Prior Guest'), ('HA', 'HomeAway/VRBO'), ('VRBO', 'VRBO'), ('Agent', 'Agent'), ('Website', 'Website'), ('Guest', 'Guest Referral'), ('Other', 'Other')], max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('rental_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_fee_note', models.CharField(blank=True, max_length=200)),
                ('tax_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('Check', 'Check'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('PayPal', 'PayPal'), ('Venmo', 'Venmo'), ('Amazon', 'Amazon')], max_length=50)),
                ('payment_contract_how_many', models.CharField(blank=True, choices=[('1', '1 Payment'), ('2', '2 Payments'), ('HA', 'HomeAway')], max_length=5)),
                ('payment_1_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_1_date', models.DateField(blank=True, null=True)),
                ('payment_1_note', models.TextField(blank=True)),
                ('payment_1_deposit', models.CharField(blank=True, max_length=50)),
                ('payment_2_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_2_date', models.DateField(blank=True, null=True)),
                ('payment_2_note', models.TextField(blank=True)),
                ('payment_2_deposit', models.CharField(blank=True, max_length=50)),
                ('payment_deposit_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_returned', models.BooleanField(default=False)),
                ('confirm_sent', models.BooleanField(default=False)),
                ('precheck_email_sent', models.BooleanField(default=False)),
                ('contract_rules_sent', models.BooleanField(default=False)),
                ('contract_rules_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Signed', 'Signed')], max_length=20)),
                ('contract_pet_sent', models.BooleanField(default=False)),
                ('contract_pet_status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Signed', 'Signed')], max_length=20)),
                ('pin', models.CharField(blank=True, max_length=10)),
                ('ha_reservation', models.CharField(blank=True, max_length=200)),
                ('ha_name', models.CharField(blank=True, max_length=200)),
                ('ha_checkin', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.guest')),
            ],
            options={
                'ordering': ['-arrive_date'],
            },
        ),
    ]
