# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_salutation', models.TextField(blank=True)),
                ('email_body', models.TextField(blank=True)),
                ('email_closing', models.TextField(blank=True)),
                ('email_sig', models.TextField(blank=True)),
                ('email_letter', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
