# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=5)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='USA', max_length=100)),
                ('phone_home', models.CharField(blank=True, max_length=30)),
                ('phone_cell', models.CharField(blank=True, max_length=30)),
                ('phone_cell2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('pin', models.CharField(blank=True, max_length=4)),
                ('desirability', models.CharField(blank=True, choices=[('Great', 'Great'), ('OK', 'OK'), ('Bad', 'Bad'), ('Do Not Rent', 'Do Not Rent')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ha_name', models.CharField(blank=True, max_length=200, verbose_name='HA Name')),
                ('ha_reservation', models.CharField(blank=True, max_length=200, verbose_name='HA Reservation #')),
                ('ha_email', models.EmailField(blank=True, max_length=254, verbose_name='HA Email')),
                ('ha_phone', models.CharField(blank=True, max_length=30, verbose_name='HA Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
