# Generated by Django 4.2.29 on 2026-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=20)),
                ('frequency_days', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_months', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
